// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jobnfahrqsjczjdorbur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvYm5mYWhycXNqY3pqZG9yYnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNDkxOTMsImV4cCI6MjA3NTgyNTE5M30.S0OruJI-B4E92BqHLrzeKW_tv1AzNDRmg1l9ToS-bMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});